/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tools;

import Entities.Commande;
import Services.CommandeService;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.util.Date;
import java.util.List;

/**
 *
 * @author moham
 */
public class PDFCart {

 public void pdfGeneration() throws FileNotFoundException, DocumentException, MalformedURLException, IOException, URISyntaxException {
        Document document = new Document();
        CommandeService ps = new CommandeService ();
        List<Commande> order= ps.ShowCommande();
        PdfWriter.getInstance(document, new FileOutputStream (new File ("commande.pdf")));
        document.open();
        document.addTitle("Commande");
        document.addSubject("Using iText");
        document.addKeywords("Java, PDF, iText");
        document.addAuthor("Gclaim");
        document.addCreator("Gclaim admin");
        Paragraph preface = new Paragraph();

        Paragraph titre =new Paragraph (" Gclaim Commande");
        titre.setAlignment (Element.ALIGN_CENTER);

        // Will create: Report generated by: _name, _date
        preface.add(new Paragraph(
                "Report generated by: " + System.getProperty("user.name") + ", " + new Date ()));
        preface.add(new Paragraph(
                "This document describes all the bills "));
        preface.setAlignment (Element.ALIGN_CENTER);
        document.add (titre);
        document.add(preface);
      
        // Start a new page
//        document.newPage();

        PDFProd pdf=new PDFProd ();
        PdfPTable table = new PdfPTable(4);

        PdfPCell c1 = new PdfPCell(new Phrase("Username"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Total"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("DateAchat"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Livrer"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

       

        

       

        table.setHeaderRows(1);
        for (Commande o:order) {
            table.addCell(String.valueOf (o.getUser().getUsername()));
            table.addCell(String.valueOf (o.getTotal()));
            table.addCell(String.valueOf (o.getDate_achat()));
            table.addCell(String.valueOf (o.isLivrer()));
           
         
            
        }

        document.add (table);
        document.close ();

 }
  
}
