/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tools;

import Entities.Equipe;
import Entities.Tournoi;
import Entities.Utilisateur;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;

import java.awt.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.List;
//import javax.swing.text.Document;
import Services.ServiceTournoi;
import Services.ServiceEquipe;

import com.itextpdf.text.Phrase;
import static com.itextpdf.text.pdf.BidiOrder.PDF;
import static com.itextpdf.text.pdf.PdfName.PDF;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.util.Date;
import javafx.scene.image.ImageView;
import static javax.print.DocFlavor.BYTE_ARRAY.PDF;
import static javax.print.DocFlavor.INPUT_STREAM.PDF;

/**
 *
 * @author user
 */
public class PDFTourn {

 public void pdfGeneration(Tournoi t,Utilisateur ut) throws FileNotFoundException, DocumentException, MalformedURLException, IOException, URISyntaxException {
        Document document = new Document();
        ServiceEquipe es = new ServiceEquipe ();

     
       
        PdfWriter.getInstance(document, new FileOutputStream (new File ("tournois.pdf")));
        document.open();
        document.addTitle("Badge Equipe");
        document.addSubject("Using iText");
        document.addKeywords("Java, PDF, iText");
        document.addAuthor("Gclaim");
        document.addCreator("Gclaim admin");
        Paragraph preface = new Paragraph();

        Paragraph titre =new Paragraph (" Gclaim Tournois");
        titre.setAlignment (Element.ALIGN_CENTER);

        // Will create: Report generated by: _name, _date
        preface.add(new Paragraph(
                "Badge généré par: " + ut.getUsername() + ", " + new Date ()));
        preface.add(new Paragraph(
                t.getNomtournoi()));
        preface.setAlignment (Element.ALIGN_CENTER);
        document.add (titre);
        document.add(preface);
      
        // Start a new page
//        document.newPage();

        PDFTourn pdf=new PDFTourn ();
        PdfPTable table = new PdfPTable(2);

        PdfPCell c1 = new PdfPCell(new Phrase("nom"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("email"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

      

        

       

        table.setHeaderRows(1);
         
            
                for(Utilisateur Ut : es.afficheUtilisateursduneEqu(es.afficheEquipeUt(ut.getId()).get(0)))
                {
        System.out.println(Ut.getEmail());
        System.out.println(Ut.getUsername());
            table.addCell(String.valueOf (Ut.getEmail()));
            table.addCell(String.valueOf (Ut.getUsername()));
 

        }

        document.add (table);
        
        document.close ();

 }
 }
  
